### ISSUE TITLE
Add support for "knames" and "kticks" as input arguments for band unfolding

### ISSUE THREAD

**Issue by uthpalaherath** [romerogroup/pyprocar#178]
In PyProcar v6.x, the parameters `kticks` and `knames` don't do anything for band unfolding. 

E.g., 

The following code, 

```
pyprocar.unfold(
    code="vasp",
    mode="plain",
    unfold_mode="both",
    fermi=6.7495,
    dirname="/Users/uthpala/Library/CloudStorage/GoogleDrive-ukh0001@mix.wvu.edu/My Drive/Research/Projects/PyProcar/rutgers-examples/band-unfolding/MgB2/pyprocar6",
    elimit=[-10, 10],
    supercell_matrix=np.diag([2, 2, 2]),
    show=False,
    kticks=[0, 36, 54, 86, 110, 147, 165, 199],
    knames=["$Gamma$", "K", "M", "$Gamma$", "A", "H", "L", "A"],
    savefig="MgB2-unfolded.pdf",
)
```

gives, 

<img width="877" alt="Image" src="https://github.com/user-attachments/assets/628b9d88-3e64-429b-aaef-69d1f012a60b" />

Additionally, there is an empty legend at the center of the plot. 

_Just documenting this for the record. I'll try to look into fixing this._
_-Uthpala_

**Comment by lllangWV** [comment]
The issue is here. I guess the logic is failing here probably because the `self.kpath` is None

[ebs_plot.py:614:642](https://github.com/romerogroup/pyprocar/blob/ec357097328e82b98839edb5ad7562979fac2432/pyprocar/plotter/ebs_plot.py#L603)
```python
def set_xticks(
        self,
        tick_positions: List[int] = None,
        tick_names: List[str] = None,
        color: str = "black",
    ):
        """A method to set the x ticks

        Parameters
        ----------
        tick_positions : List[int], optional
            A list of tick positions, by default None
        tick_names : List[str], optional
            A list of tick names, by default None
        color : str, optional
            A color for the ticks, by default "black"
        """

        if self.kpath is not None:
            if tick_positions is None:
                tick_positions = self.kpath.tick_positions
            if tick_names is None:
                tick_names = self.kpath.tick_names
            for ipos in tick_positions:
                self.ax.axvline(self.x[ipos], color=color)

            self.ax.set_xticks(self.x[tick_positions])
            self.ax.set_xticklabels(tick_names)
            self.ax.tick_params(**self.config.major_x_tick_params)
```

**Comment by lllangWV** [comment]
I just pushed a change, I believe the issue is fixed now. Can you try to see if it works for your example?

**Comment by uthpalaherath** [comment]
That fixes it perfectly! Thanks, @lllangWV. 

<img width="997" alt="Image" src="https://github.com/user-attachments/assets/db9e3331-dfdd-4558-88d4-be89d60f6564" />

We still have the empty legend at the center of the plot. Should we get rid of it unless there is content in it?
